services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/config/otel-collector.yaml"]
    volumes:
      - ./config:/etc/config
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"
      - "16686:16686"
